python main.py \
--image_dir ../iu_xray/images/ \
--ann_path ../iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 1 \
--save_dir results/iu_xray_debug \
--step_size 100 \
--gamma 0.1 \
--seed 9223 \
--n_gpu 8 
