CUDA_VISIBLE_DEVICES=1 python main.py \
--model r2genaugv3abrm \
--image_dir data/iu_xray/images/ \
--ann_path data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 40 \
--epochs 100 \
--num_layers 4 \
--save_dir results/iu_xray_augv3abv1 \
--step_size 50 \
--gamma 0.1 \
--n_gpu 1 \
--seed 9223